var BACKGROUNDS = {
    "ARM1 Chip": "arm1_chip.gif",
    "Death Star": "death_star.jpg",
    "Pattern 02": "pattern02.jpg",
    "Pattern 19": "pattern19.jpg",
    "Bauhaus": "bauhaus.jpg",
    "Doradus": "doradus.jpg",
    "Pattern 03": "pattern03.jpg",
    "Pattern 20": "pattern20.jpg",
    "BBC Basic": "bbc_basic.gif",
    "Dunes": "dunes.jpg",
    "Pattern 04": "pattern04.jpg",
    "Pattern 21": "pattern21.jpg",
    "BBC micro:bit back": "bbc_microbit_back.jpg",
    "Edinburgh": "edinburgh.jpg",
    "Pattern 05": "pattern05.jpg",
    "Phosphor Sea": "phosphor_sea.jpg",
    "BBC micro:bit front": "bbc_microbit_front.jpg",
    "Field": "field.jpg",
    "Pattern 06": "pattern06.jpg",
    "Pong": "pong.jpg",
    "BBC micro:bit logo": "bbc_microbit_logo.jpg",
    "Fish": "fish.jpg",
    "Pattern 07": "pattern07.jpg",
    "Python Powered": "python_powered.jpg",
    "BBC Micro": "bbc_micro.jpg",
    "Forest Lake": "forest_lake.jpg",
    "Pattern 08": "pattern08.jpg",
    "Raspberry Pi": "raspberry_pi.jpg",
    "BBC Owl": "bbc_owl.jpg",
    "Forest Stream": "forest_stream.jpg",
    "Pattern 09": "pattern09.jpg",
    "Beach": "beach.jpg",
    "Guido van Rossum": "guido.jpg",
    "Pattern 10": "pattern10.jpg",
    "Seaside": "seaside.jpg",
    "Belfast": "belfast.jpg",
    "London": "london.jpg",
    "Pattern 11": "pattern11.jpg",
    "Servers": "servers.jpg",
    "Bluebells": "bluebells.jpg",
    "Mars": "mars.jpg",
    "Pattern 12": "pattern12.jpg",
    "Skulls": "skulls.jpg",
    "Cardiff": "cardiff.jpg",
    "Monument Valley": "monument_valley.jpg",
    "Pattern 13": "pattern13.jpg",
    "Snow": "snow.jpg",
    "Circuit": "circuit.jpg",
    "Moon": "moon.jpg",
    "Pattern 14": "pattern14.jpg",
    "Solar System": "solar_system.jpg",
    "Cloudy Lake": "cloudy_lake.jpg",
    "Mountain River": "mountain_river.jpg",
    "Pattern 15": "pattern15.jpg",
    "Sunset": "sunset.jpg",
    "Colossus": "colossus.jpg",
    "Office": "office.jpg",
    "Pattern 16": "pattern16.jpg",
    "Winter Sun": "winter_sun.jpg",
    "Computer Class": "computer_class.jpg",
    "Old Computer": "old_computer.jpg",
    "Pattern 17": "pattern17.jpg",
    "Country Lane": "country_lane.jpg",
    "Pattern 01": "pattern01.jpg",
    "Pattern 18": "pattern18.jpg"
};
